// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChSTLtAEwfrJn40mcfnGFvwNLbXv--aSk',
    appId: '1:105825610600:web:a6f60ef24685a24a2c44dd',
    messagingSenderId: '105825610600',
    projectId: 'my-hacon',
    authDomain: 'my-hacon.firebaseapp.com',
    storageBucket: 'my-hacon.firebasestorage.app',
    measurementId: 'G-S0FPW50R23',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPw8hEguP90MHH5XBwTec5Bg4iVFiMhs0',
    appId: '1:105825610600:android:0ad1c5d3e63945282c44dd',
    messagingSenderId: '105825610600',
    projectId: 'my-hacon',
    storageBucket: 'my-hacon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9_Qr8tmuXmitMyyiXSkj2hIF_-btoA8U',
    appId: '1:105825610600:ios:1b36d11acb84ed4b2c44dd',
    messagingSenderId: '105825610600',
    projectId: 'my-hacon',
    storageBucket: 'my-hacon.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9_Qr8tmuXmitMyyiXSkj2hIF_-btoA8U',
    appId: '1:105825610600:ios:1b36d11acb84ed4b2c44dd',
    messagingSenderId: '105825610600',
    projectId: 'my-hacon',
    storageBucket: 'my-hacon.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChSTLtAEwfrJn40mcfnGFvwNLbXv--aSk',
    appId: '1:105825610600:web:9e91cca0a08036492c44dd',
    messagingSenderId: '105825610600',
    projectId: 'my-hacon',
    authDomain: 'my-hacon.firebaseapp.com',
    storageBucket: 'my-hacon.firebasestorage.app',
    measurementId: 'G-6TM17WSB9F',
  );

}